Repository Valkiria-Project/SISEM-Android, pull requests merged in 2023-09, with the labels that each got.

#65 [Feature]: Wrap up ImageConfirmation screen
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/BitmapExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/utils/CameraUtils.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/CameraScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/ReportNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/FindingsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  app/src/main/res/values/strings.xml
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/button/ButtonView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/props/ButtonStyle.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/button/ButtonUiModel.kt
Labels: feature

#66 [Feature]: Add QA environment
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/di/BearerNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/auth/AuthNetworkModule.kt
  gradle/libs.versions.toml
  uicomponents/build.gradle.kts
  uicomponents/src/main/res/drawable/ic_medicine.xml
Labels: enhancement, feature

#71 [Feature]: Pre Populate PreOperational ViewModel with FormData
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/AuthCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/dao/AccessTokenDao.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/PreOperationalRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/PreOperationalRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/SegmentedSwitchResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/SegmentedSwitchModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/PreOperationalRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/usecases/GetPreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
Labels: bug, enhancement

#73 [Fix]: Add logic for Pre Operational inputs validation
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DigitsTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FilledTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorycheck/InventoryCheckComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
Labels: bug, enhancement

#75 [Feature]: Send Novelty as part of the Pre Operational request
  app/build.gradle.kts
  app/src/debug/res/values/strings.xml
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/PreOperationalRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/BodyRowType.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/FooterBodyModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/footer/BusinessFooterModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/PreOperationalRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/usecases/GetRole.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/report/model/AddFindingIdentifier.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/PreOpNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/ReportNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportRoleScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/res/values/strings.xml
  app/src/release/res/values/strings.xml
  app/src/staging/res/values/strings.xml
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/chip/FilterChipView.kt
Labels: feature

#78 [Fix]: Logout of other users if the administrator authenticates
  app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
Labels: bug, enhancement

#79 [Chore]: Bump version to 0.1.1
  app/build.gradle.kts
Labels: chore

#80 [Bugfix]: SMA-174
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ChipSelectionResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ContentHeaderResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/DropDownResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/HeaderResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/InfoCardResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/SliderResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/ChipSectionItemResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/DropDownItemResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/FindingsDetailResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/ReportsDetailResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/header/HeaderResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/props/TextResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/screen/ScreenResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/BodyRowType.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ChipOptionsModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ChipSelectionModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ContentHeaderModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/DropDownModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/HeaderModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/InfoCardModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/InventoryCheckModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/SliderModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/ChipSectionModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/FindingDetailModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/FindingsDetailModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/PillModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/ReportDetailModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/ReportsDetailModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/header/BusinessHeaderModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/props/TextModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/screen/ScreenModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/bottomsheet/FindingsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/changepassword/ChangePasswordViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/deviceauth/DeviceAuthViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/HeaderSection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/card/InfoCardUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/chip/ChipSectionItemUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/dropdown/DropDownItemUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/report/ReportsDetailUiModel.kt
  uicomponents/src/main/res/drawable/ic_extinguisher.xml
Labels: bug

#77 [Feature]: PreOperational adjustments
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ChipSelectionResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ContentHeaderResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/DropDownResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/HeaderResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/InfoCardResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/SliderResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/ChipSectionItemResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/DropDownItemResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/FindingsDetailResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/ReportsDetailResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/header/HeaderResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/props/TextResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/screen/ScreenResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/BodyRowType.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ChipOptionsModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ChipSelectionModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ContentHeaderModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/DropDownModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/HeaderModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/InfoCardModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/InventoryCheckModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/SliderModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/ChipSectionModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/FindingDetailModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/FindingsDetailModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/PillModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/ReportDetailModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/ReportsDetailModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/footer/BusinessFooterModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/header/BusinessHeaderModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/props/TextModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/screen/ScreenModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/bottomsheet/FindingsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/changepassword/ChangePasswordViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/deviceauth/DeviceAuthViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/HeaderSection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ButtonComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/card/InfoCardUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/chip/ChipSectionItemUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/dropdown/DropDownItemUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/report/ReportsDetailUiModel.kt
  uicomponents/src/main/res/drawable/ic_extinguisher.xml
Labels: enhancement

#82 [Bugfix]: Add Map with Menu
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ChipSelectionResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/ChipSelectionItemResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/footer/FooterResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ChipSelectionModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/footer/BusinessFooterModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/MainActivity.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/changepassword/ChangePasswordScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/WindowExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/deviceauth/DeviceAuthScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportRoleScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/FooterSection.kt
  app/src/main/res/values/strings.xml
  uicomponents/build.gradle.kts
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/button/ButtonView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/banner/BannerComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ButtonComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipOptionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/detailedinfolist/DetailedInfoListComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/finding/FindingComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorycheck/InventoryCheckComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/label/LabelComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/richlabel/RichLabelComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/segmentedswitch/SegmentedSwitchComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/termsandconditions/TermsAndConditionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/PasswordTextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/props/ScreenProps.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/chip/ChipSelectionItemUiModel.kt
Labels: bug

#83 [Bugfix]: Add location logic
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AuditInterceptor.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/TextFieldResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/di/ApplicationModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/BearerNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/auth/AuthNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/qualifiers/Qualifiers.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/TextFieldModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/LocationExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/DrawerContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/DrawerMenuItemModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItem.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItemsComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  gradle/libs.versions.toml
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FilledTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/segmentedswitch/SegmentedSwitchComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/textfield/TextFieldUiModel.kt
Labels: bug

#85 [Bugfix]: Add DateTextFieldView logic
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DateTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/mocks/TextFieldUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/props/TextFieldStyle.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
  uicomponents/src/main/res/drawable/ic_update.xml
Labels: bug

#87 [Chore]: Add support for Firebase FCM Push Notifications
  app/build.gradle.kts
  app/src/debug/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/skgtecnologia/sisem/SisemApplication.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notifications/MessagingService.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/CameraScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/release/google-services.json
  app/src/staging/google-services.json
  build.gradle.kts
  gradle/libs.versions.toml
Labels: feature

#88 [Chore]: Version 0.2.0 testing
  .idea/shelf/feat__DigitsTextFieldView.xml
  .idea/shelf/feat__Make_Sisem_WebSocket_ready.xml
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/AuthCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/dao/AccessTokenDao.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/AuthCardsRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/OperationRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/OperationCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/dao/OperationDao.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/PreOperationalRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/InventoryCheckResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/report/ReportRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/AuthRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/OperationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/changepassword/usecases/GetLoginNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/changepassword/usecases/OnCancel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/InventoryCheckModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/SegmentedSwitchModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/operation/OperationRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/operation/usecases/ObserveOperationConfig.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/operation/usecases/RetrieveOperationConfig.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/model/PreOperationalIdentifier.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/splash/usecases/GetStartupState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/report/ReportContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/changepassword/ChangePasswordScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/deviceauth/DeviceAuthScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/CameraScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/ReportNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportRoleScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DigitsTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/banner/OnBannerHandler.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorycheck/InventoryCheckComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/segmentedswitch/SegmentedSwitchComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/mocks/InventoryCheckUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/inventorycheck/InventoryCheckUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/segmentedswitch/SegmentedSwitchUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/textfield/TextFieldUiModel.kt
  uicomponents/src/test/snapshots/images/com.valkiria.uicomponents.components.finding_FindingComponentPaparazziTest_snapFindingComponent.png
  uicomponents/src/test/snapshots/images/com.valkiria.uicomponents.components.segmentedswitch_SegmentedSwitchComponentPaparazziTest_snapDeviceAuthSegmentedSwitchComponent.png
Labels: bug, chore

#90 [Bugfix]: Data storage related fixes
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/AuthCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/OperationCacheDataSource.kt
Labels: bug

#91 [Fix]: Bottom sheet problem solved
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/wounds/WoundsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/wounds/WoundsViewModel.kt
Labels: bug

#92 [Bugfix]: Add Report Screen
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportRoleScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  gradle/libs.versions.toml
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/mocks/TextFieldUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/model/props/TextFieldStyle.kt
  uicomponents/src/main/res/drawable/ic_identification.xml
  uicomponents/src/main/res/drawable/ic_identification_number.xml
Labels: bug
