Repository Valkiria-Project/SISEM-Android, pull requests merged in 2023-10, with the labels that each got.

#93 [Feature]: Add AccessTokenAuthenticator
  app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/extensions/RetrofitExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenAuthenticator.kt
  app/src/main/java/com/skgtecnologia/sisem/di/BearerNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/AuthRepository.kt
Labels: feature

#95 [Feature]: Add DatePickerTextFieldView
  uicomponents/build.gradle.kts
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
Labels: enhancement, feature

#94 [Chore]: Version 0.3.0 testing
  app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/extensions/RetrofitExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenAuthenticator.kt
  app/src/main/java/com/skgtecnologia/sisem/di/BearerNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/AuthRepository.kt
  uicomponents/build.gradle.kts
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
Labels: bug

#96 [Chore]: Merge back (#94)
  app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/extensions/RetrofitExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenAuthenticator.kt
  app/src/main/java/com/skgtecnologia/sisem/di/BearerNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/AuthRepository.kt
  uicomponents/build.gradle.kts
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
Labels: chore

#100 [Fix]: adjust info card component
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
Labels: bug

#103 [BugFix]: SMA-181
  app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/CameraScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/ReportNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  app/src/main/res/values/strings.xml
Labels: bug

#105 [BugFix]: SMA-177 & SMA-202
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/domain/login/model/LegalContentModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/login/model/LoginLink.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/report/ReportContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyBackComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyFrontComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginHeaderSection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/legal/LegalContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/footer/MenuFooterComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/CrewMemberItem.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/MenuHeaderComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItem.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/HeaderSection.kt
  uicomponents/build.gradle.kts
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/banner/BannerView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/button/ImageButtonView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/detailedinfolist/DetailedInfoListComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/slider/SliderComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/PasswordTextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
Labels: bug

#106 [BugFix]: SMA-223 -> CP HU 00272 CA 01
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportViewModel.kt
  app/src/main/res/values/strings.xml
Labels: bug

#110 [Bugfix]: Finish DatePickerTextFieldView
  app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/MedicalHistoryRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/remote/MedicalHistoryRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/medsselector/MedsSelectorResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/MedicalHistoryRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/GetMedicineScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/SendMedicalHistory.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/dropdown/DropDownComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/dropdown/DropDownContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/wounds/WoundsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medsselector/MedicineViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/vitalsings/VitalSignsViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  gradle/libs.versions.toml
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ButtonComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/dropdown/DropDownItemUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/stepper/StepperUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/timepicker/TimePickerComponent.kt
  uicomponents/src/main/res/drawable/ic_add.xml
Labels: enhancement, feature

#108 [Bugfix]: SMA-183
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/model/NoveltyBody.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AuditInterceptor.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/textfield/TextFieldResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/model/Novelty.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/report/model/ImageModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/BitmapExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/PreOpNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/ReportNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  gradle/libs.versions.toml
Labels: bug

#112 [Feature]: Migrate the logic for images to use a @Multipart request
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/PreOperationalRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/PreOperationalApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/PreOperationalRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/model/NoveltyBody.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/model/SavePreOperationalBody.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/extensions/MultiPartExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/images/ImageBody.kt
  app/src/main/java/com/skgtecnologia/sisem/data/report/remote/ReportApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/report/remote/ReportRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/report/remote/model/ReportBody.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/report/model/ImageModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/FileExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/utils/CameraUtils.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: bug, enhancement, feature

#111 [Bugfix]: Version 0.4.0
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/remote/AuthCardsApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/PreOperationalRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/PreOperationalApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/PreOperationalRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/model/NoveltyBody.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/extensions/MultiPartExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/images/ImageBody.kt
  app/src/main/java/com/skgtecnologia/sisem/data/report/remote/ReportApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/report/remote/ReportRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/report/remote/model/ReportBody.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BannerModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/model/Novelty.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/report/model/ImageModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/BitmapExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/FileExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/utils/CameraUtils.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/PreOpNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/ReportNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DigitsTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorycheck/InventoryCheckComponent.kt
Labels: bug, enhancement

#113 [Fix]: Add ellipse to pill
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
Labels: bug

#116 [Feature]: Add Stepper Component
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/MedicalHistoryRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/remote/MedicalHistoryRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/remote/model/HumanBodyBody.kt
  app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/remote/model/MedicalHistoryBody.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AuditInterceptor.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/MedicalHistoryRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/SendMedicalHistory.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/dropdown/DropDownComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyBackComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyFrontComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/wounds/WoundsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/chip/OptionChipView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipOptionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/FiltersComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/detailedinfolist/DetailedInfoListComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/humanbody/HumanBodyUi.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/segmentedswitch/SegmentedSwitchComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/signature/CrewMemberSignatureComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/signature/SignatureComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/stepper/StepperComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/stepper/StepperUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/extensions/FileExtensions.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/extensions/TextFieldExtensions.kt
Labels: feature

#118 [Bugfix]: SMA-289
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
Labels: bug

#119 [Bugfix]: SMA-228
  app/build.gradle.kts
  uicomponents/src/main/res/drawable/ic_accessories.xml
  uicomponents/src/main/res/drawable/ic_plate.xml
Labels: bug

#121 [Bugfix]: SMA-288 Part 1
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/model/OperationEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/remote/model/OperationResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/dropdown/DropDownResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/termsandconditions/TermsAndConditionsResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/OperationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/ViewModelExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/dropdown/DropDownComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/wounds/WoundsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/chip/OptionChipView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DigitsTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FilledTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/BodyRowModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ButtonUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ImageButtonComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ImageButtonSectionComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ImageButtonSectionUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ImageButtonUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipOptionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipOptionsUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/FiltersUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/detailedinfolist/DetailedInfoListUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/dropdown/DropDownUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/finding/FindingUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/fingerprint/FingerprintUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/footer/FooterBodyUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/header/HeaderUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/humanbody/HumanBodyUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorycheck/InventoryCheckComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorycheck/InventoryCheckUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/label/LabelUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/medsselector/MedsSelectorUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/richlabel/RichLabelUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/segmentedswitch/SegmentedSwitchUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/signature/CrewMemberSignatureUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/signature/SignatureUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/slider/SliderUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/stepper/StepperUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/termsandconditions/TermsAndConditionsUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/PasswordTextFieldUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/timepicker/TimePickerUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/extensions/FileExtensions.kt
  uicomponents/src/main/res/drawable/ic_driver.xml
Labels: bug

#122 [Bugfix]: SMA-288 Part 2
  app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/MedicalHistoryRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ImageButtonSectionComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/InputUiModel.kt
Labels: bug
