Repository Valkiria-Project/SISEM-Android, pull requests merged in 2023-08, with the labels that each got.

#16 [Feature]: Show MapBox map
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/model/AccessTokenEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/model/AccessTokenResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/model/AuthenticateBody.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/converters/CacheConverters.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/login/model/AccessTokenModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/SisemComposeApp.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
  app/src/main/res/values/strings.xml
  settings.gradle.kts
  uicomponents/build.gradle.kts
  uicomponents/src/main/java/com/valkiria/uicomponents/components/map/MapComponent.kt
  uicomponents/src/main/res/drawable/ic_ambulance_marker.xml
  uicomponents/src/main/res/drawable/ic_marker.xml
  uicomponents/src/main/res/values/strings.xml
Labels: feature

#17 [Feature}: Add Turn / News Screen
  app/src/main/java/com/skgtecnologia/sisem/di/CoreDatabaseModule.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/SisemComposeApp.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/CardComponent.kt
  uicomponents/src/main/res/drawable/ic_calendar.xml
  uicomponents/src/main/res/drawable/ic_clock.xml
  uicomponents/src/main/res/drawable/ic_news.xml
Labels: feature

#22 [Feature]: HU 271 Auth Cards
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/AuthCardsRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/cache/AuthCardsCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/cache/dao/ConfigDao.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/cache/model/ConfigEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/remote/AuthCardsApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/remote/AuthCardsRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/remote/model/ConfigResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ChipSectionResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/CrewMemberCardResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/DetailResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ListTextResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/PillResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ReportsDetailResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/screen/Params.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreDatabaseModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/authcards/AuthCardsNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/authcards/AuthCardsRepositoryModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/AuthCardsRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/AuthCardsIdentifier.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/ConfigModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/usecases/Config.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/usecases/GetAuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/usecases/GetConfig.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/BodyRowType.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ChipSectionModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/CrewMemberCardModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/DetailModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ListTextModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/PillModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ReportsDetailModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/SisemComposeApp.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/ReportContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/ReportDetailContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/ChipSectionUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/CrewMemberCardComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/CrewMemberCardUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/DetailUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/ReportsDetailUiModel.kt
  uicomponents/src/main/res/drawable/ic_aux.xml
  uicomponents/src/main/res/drawable/ic_doctor.xml
  uicomponents/src/main/res/drawable/ic_driver.xml
Labels: feature

#27 [Feature]: Menu View
  app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/AuthCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/dao/AccessTokenDao.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/model/AccessTokenEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/model/PreOperationalEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/model/TurnEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/model/AccessTokenResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/model/AuthenticateBody.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/model/LogoutResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/model/PreOperationalResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/model/TurnResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/AuthCardsRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/cache/model/ConfigEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/remote/model/ConfigResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/FingerprintResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/AuthRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/model/AccessTokenModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/model/PreOperationalModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/model/TurnModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/usecases/GetAllAccessTokens.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/usecases/Login.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/usecases/Logout.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/AuthCardsRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/AuthCardsIdentifier.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/ConfigModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/usecases/GetAuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/SisemComposeApp.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/DrawerContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/footer/MenuFooterComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/CrewMemberItem.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/CrewMemberItemModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/MenuHeaderComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItem.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItemModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItemsComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/theme/Theme.kt
  app/src/main/res/drawable/ic_ambulance.xml
  app/src/main/res/drawable/ic_logout.xml
  app/src/main/res/values/strings.xml
  uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/CrewMemberCardComponent.kt
  uicomponents/src/main/res/drawable/ic_certifications.xml
  uicomponents/src/main/res/drawable/ic_hceud.xml
  uicomponents/src/main/res/drawable/ic_incidents.xml
  uicomponents/src/main/res/drawable/ic_inventory.xml
  uicomponents/src/main/res/drawable/ic_notification.xml
Labels: feature

#29 [Fix]: Make json properties snake case
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/props/MarginsResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/screen/Params.kt
Labels: bug

#32 [Feature]: Add navigation logic for LoginScreen
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/domain/login/model/LoginIdentifier.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/SisemComposeApp.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/deviceauth/DeviceAuthUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/LoginNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
Labels: feature

#35 [Chore]: Migrate to libs.versions.toml and update agp to 8.1.0
  .idea/kotlinc.xml
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/ReportContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/HeaderSection.kt
  build.gradle.kts
  buildscripts/detekt.gradle
  buildscripts/setup.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  uicomponents/build.gradle.kts
Labels: chore

#36 [Feat]: Add logic to persist ambulance code and create package intended for operation
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/AuthCardsRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/cache/AuthCardsCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/cache/dao/ConfigDao.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/remote/AuthCardsApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/remote/AuthCardsRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/OperationRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/OperationCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/dao/OperationDao.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/model/OperationEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/remote/OperationApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/remote/OperationRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/remote/model/OperationResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreDatabaseModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/operation/OperationNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/operation/OperationRepositoryModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/AuthCardsRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/usecases/GetConfig.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/operation/OperationRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/operation/usecases/GetConfig.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/operation/usecases/StoreAmbulanceCode.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
Labels: enhancement

#42 [Fix]: Chip section action show bottom sheet
  app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/ChipSectionModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/FindingsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/CrewMemberCardComponent.kt
  uicomponents/src/main/res/drawable/ic_finding.xml
Labels: enhancement

#47 [Refactor]: Add arrangement to model
  app/src/main/java/com/skgtecnologia/sisem/data/remote/adapters/ArrangementAdapter.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ButtonResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ChipOptionsResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ChipResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ContentHeaderResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/CrewMemberCardResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/DetailedInfoListResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/FindingResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/InventoryCheckResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/LabelResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/PasswordTextFieldResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/RichLabelResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/SegmentedSwitchResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/TermsAndConditionsResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/TextFieldResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ButtonModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ChipModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ChipOptionsModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ContentHeaderModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/CrewMemberCardModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/DetailedInfoListModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/FindingModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/InventoryCheckModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/LabelModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/PasswordTextFieldModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/RichLabelModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/SegmentedSwitchModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/TermsAndConditionsModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/TextFieldModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/header/HeaderModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ButtonUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/CrewMemberCardUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/detailedinfolist/DetailedInfoListComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/detailedinfolist/DetailedInfoListUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/finding/FindingUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/label/LabelUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/passwordtextfield/PasswordTextFieldUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/richlabel/RichLabelUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/segmentedswitch/SegmentedSwitchUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/termsandconditions/TermsAndConditionsUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/ButtonUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/ChipUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/FindingUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/LabelUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/PasswordTextFieldUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/RichLabelUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/SegmentedSwitchUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/TermsAndConditionsUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/TextFieldUiModelMocks.kt
Labels: enhancement

#48 [Refactor]: Add row component and arrangement
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/FindingsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/footer/MenuFooterComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/MenuHeaderComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/DrawerItemInfo.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItemModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/HeaderSection.kt
  app/src/main/res/values/strings.xml
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ButtonComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/detailedinfolist/DetailedInfoListComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/label/LabelComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/passwordtextfield/PasswordTextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/passwordtextfield/PasswordTextFieldUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/richlabel/RichLabelComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/termsandconditions/TermsAndConditionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/PasswordTextFieldUiModelMocks.kt
  uicomponents/src/test/snapshots/images/com.valkiria.uicomponents.components.detailedinfolist_DetailedInfoListComponentPaparazziTest_snapDetailedInfoListComponent.png
  uicomponents/src/test/snapshots/images/com.valkiria.uicomponents.components.label_LabelComponentPaparazziTest_snapLabelComponent.png
  uicomponents/src/test/snapshots/images/com.valkiria.uicomponents.components.passwordtextfield_PasswordTextFieldComponentPaparazziTest_snapLoginPasswordTextFieldComponent.png
Labels: enhancement

#45 [Feature]: PreOperational UI elements
  .idea/shelf/feat__DigitsTextFieldView/shelved.patch
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/PreOperationalApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ChipOptionsResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/ContentHeaderResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/CrewMemberCardResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/InventoryCheckResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/ChipSectionResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/DetailResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/InventoryCheckItemResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/PillResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/header/HeaderResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/props/TextResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/di/authcards/AuthCardsNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/operation/OperationNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/ChipOptionsModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/InventoryCheckModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/FindingsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  gradle/libs.versions.toml
  uicomponents/build.gradle.kts
  uicomponents/out/failures/com.valkiria.uicomponents.components.loader_LoaderComponentPaparazziTest_snapLoaderComponent.png
  uicomponents/out/failures/com.valkiria.uicomponents.components.passwordtextfield_PasswordTextFieldComponentPaparazziTest_snapLoginPasswordTextFieldComponent.png
  uicomponents/out/failures/com.valkiria.uicomponents.components.segmentedswitch_SegmentedSwitchComponentPaparazziTest_snapDeviceAuthSegmentedSwitchComponent.png
  uicomponents/out/failures/com.valkiria.uicomponents.components.termsandconditions_TermsAndConditionsComponentPaparazziTest_snapLoginTermsAndConditionsComponent.png
  uicomponents/out/failures/com.valkiria.uicomponents.components.textfield_TextFieldComponentPaparazziTest_snapLoginUserTextFieldComponent.png
  uicomponents/out/failures/delta-com.valkiria.uicomponents.components.loader_LoaderComponentPaparazziTest_snapLoaderComponent.png
  uicomponents/out/failures/delta-com.valkiria.uicomponents.components.passwordtextfield_PasswordTextFieldComponentPaparazziTest_snapLoginPasswordTextFieldComponent.png
  uicomponents/out/failures/delta-com.valkiria.uicomponents.components.segmentedswitch_SegmentedSwitchComponentPaparazziTest_snapDeviceAuthSegmentedSwitchComponent.png
  uicomponents/out/failures/delta-com.valkiria.uicomponents.components.termsandconditions_TermsAndConditionsComponentPaparazziTest_snapLoginTermsAndConditionsComponent.png
  uicomponents/out/failures/delta-com.valkiria.uicomponents.components.textfield_TextFieldComponentPaparazziTest_snapLoginUserTextFieldComponent.png
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/DigitsTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/FilterChipView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/SuggestionChipView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ButtonComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chipoptions/ChipOptionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chipoptions/ChipOptionsUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/CrewMemberCardComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/detailedinfolist/DetailedInfoListComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/filters/FiltersComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorycheck/InventoryCheckComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorycheck/InventoryCheckItemUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorycheck/InventoryCheckUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/passwordtextfield/PasswordTextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/ChipOptionsUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/DetailedInfoListUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/FiltersUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/InventoryCheckUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/RichLabelUiModelMocks.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/props/ScreenProps.kt
  uicomponents/src/test/snapshots/images/com.valkiria.uicomponents.components.filters_FiltersComponentPaparazziTest_snapFiltersComponent.png
Labels: feature

#51 [Feature]: PreOperation All part 2
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/LabelResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/body/LabelModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/model/PreOperationalIdentifier.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/bottomsheet/FindingFormContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/bottomsheet/FindingsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/imageselection/ImageSelectionScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/PreOpNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/FooterSection.kt
  app/src/main/res/values/strings.xml
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/ButtonView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ButtonComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ButtonUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/props/TextStyle.kt
  uicomponents/src/main/res/drawable/ic_back.xml
  uicomponents/src/main/res/drawable/ic_image.xml
Labels: feature

#52 [Feature]: PreOperation All part 3
  .idea/kotlinc.xml
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/dao/AccessTokenDao.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/dao/OperationDao.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/imageselection/ImageSelectionScreen.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  uicomponents/build.gradle.kts
Labels: feature

#58 [Feature]: Update BASE_URL
  app/src/main/java/com/skgtecnologia/sisem/di/BearerNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/auth/AuthNetworkModule.kt
Labels: feature

#60 [Chore]: Migrations
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  uicomponents/build.gradle.kts
Labels: enhancement, chore

#57 [Feature]: PreOperation All part 4
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/skgtecnologia/sisem/di/operation/OperationRole.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/bottomsheet/FindingFormContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/bottomsheet/FindingsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/camera/CameraScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/camera/CameraUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/camera/CameraViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/imageselection/ImageSelectionScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/imageselection/ImageSelectionUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/imageselection/ImageSelectionViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/CameraNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/ImageSelectionNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/PreOpNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/FooterSection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/HeaderSection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/utils/CameraUtils.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/utils/MediaStoreUtils.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  uicomponents/build.gradle.kts
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/button/ButtonView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/chip/FilterChipView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/chip/SuggestionChipView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DigitsTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FilledTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chipoptions/ChipOptionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/CrewMemberCardComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/filters/FiltersComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorycheck/InventoryCheckComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/test/java/com/valkiria/uicomponents/bricks/FilledTextFieldViewPaparazziTest.kt
  uicomponents/src/test/java/com/valkiria/uicomponents/bricks/OutlinedTextFieldViewPaparazziTest.kt
Labels: feature
