Repository Valkiria-Project/SISEM-Android, pull requests merged in 2023-11, with the labels that each got.

#125 [Fix]: SMA-295 part 1, SMA-296 point 2-3, SMA-298
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/model/MedicalHistoryKeys.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/vitalsings/VitalSignsViewModel.kt
Labels: bug

#128 [Feat]: Forgot password screen and logic
  app/src/main/java/com/skgtecnologia/sisem/data/forgotpassword/ForgotPasswordRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/forgotpassword/remote/ForgotPasswordApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/forgotpassword/remote/ForgotPasswordRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/di/forgotpassword/ForgotPasswordNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/forgotpassword/ForgotPasswordRepositoryModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/forgotpassword/ForgotPasswordRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/forgotpassword/model/ForgotPasswordIdentifier.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/forgotpassword/usecases/GetForgotPasswordScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/forgotpassword/usecases/SendEmail.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  uicomponents/src/main/res/drawable/ic_email.xml
Labels: feature

#127 [Chore]: SMA-161 Part 1
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/commons/communication/EventBus.kt
  app/src/main/java/com/skgtecnologia/sisem/commons/communication/UnauthorizedEventHandler.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/authcards/remote/AuthCardsRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/changepassword/remote/ChangePasswordRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/deviceauth/remote/DeviceAuthRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/forgotpassword/remote/ForgotPasswordRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/login/remote/LoginRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/remote/MedicalHistoryRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/remote/OperationRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/PreOperationalRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/extensions/ApiCallExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/extensions/NetworkingExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenAuthenticator.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/banner/BannerResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/chip/ChipSelectionResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/error/ErrorResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/report/remote/ReportRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/login/model/LoginIdentifier.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BannerModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/ComposableExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/res/values/strings.xml
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/button/ImageButtonUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/button/ImageButtonView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/BodyRowType.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/footer/FooterUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/media/MediaActionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/media/MediaActionsUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/timepicker/TimePickerComponent.kt
  uicomponents/src/main/res/drawable/ic_camera.xml
  uicomponents/src/main/res/drawable/ic_file.xml
  uicomponents/src/main/res/drawable/ic_image.xml
  uicomponents/src/main/res/values/strings.xml
Labels: bug, feature

#131 [Feat]: Preoperational menu
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/PreOperationalRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/PreOperationalApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/PreOperationalRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/finding/FindingResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/segmentedswitch/SegmentedValueResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/PreOperationalRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/model/PreOperationalViewIdentifier.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/usecases/GetAuthCardViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/usecases/GetPreOperationalScreenView.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/AuthCardsUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/AuthCardsViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/report/FindingsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/report/ReportContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/report/ReportDetailContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOpNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/FindingContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOpViewNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/banner/finding/FindingsDetailUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/finding/FindingComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/finding/FindingUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/segmentedswitch/SegmentedValueComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/segmentedswitch/SegmentedValueUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/FindingUiModelMocks.kt
Labels: feature

#132 [Fix]: Proper handing of media actions in APH
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/textfield/TextFieldResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/addfinding/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/label/LabelComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/label/LabelUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/media/MediaActionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
  uicomponents/src/main/res/drawable/ic_trash.xml
  uicomponents/src/main/res/values/strings.xml
Labels: bug, feature

#135 [Feat]: Inventory screen and views
  app/src/main/java/com/skgtecnologia/sisem/data/inventory/InventoryRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/inventory/remote/InventoryApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/inventory/remote/InventoryRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/card/SimpleCardResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/inventorysearch/InventoryItemResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/inventorysearch/InventorySearchResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/inventory/InventoryNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/inventory/InventoryRepositoryModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/inventory/InventoryRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/inventory/model/InventoryType.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/inventory/usecases/GetInventoryInitialScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/inventory/usecases/GetInventoryViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/dropdown/DropDownContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/InventoryNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/InventoryScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/InventoryUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/InventoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/view/InventoryViewNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/view/InventoryViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/view/InventoryViewUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/view/InventoryViewViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/BodyRowType.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/SimpleCardComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/SimpleCardUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorysearch/InventoryItemUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorysearch/InventorySearchComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorysearch/InventorySearchUiModel.kt
Labels: enhancement, feature

#139 [Chore]: Bump version to 0.7.1
  app/build.gradle.kts
Labels: chore

#140 [Test]: Login ViewModel
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/login/LoginViewModelTest.kt
Labels: test

#142 [Test]: Auth cards view ViewModel
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewViewModel.kt
  app/src/test/java/com/skgtecnologia/sisem/ExampleUnitTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewViewModelTest.kt
Labels: test

#138 [Feature]: Add push notifications Ui logic part 1
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/commons/communication/NotificationEventHandler.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notifications/MessagingService.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notifications/NotificationsManager.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notifications/model/NotificationData.kt
  app/src/main/java/com/skgtecnologia/sisem/di/ApplicationModule.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/MainActivity.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
  app/src/test/java/com/skgtecnologia/sisem/commons/MainDispatcherRule.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewViewModelTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/splash/SplashViewModelTest.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/banner/BannerView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/NotificationUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/NotificationView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/NotificationUiModelMocks.kt
  uicomponents/src/main/res/drawable/ic_assigned_incident.xml
  uicomponents/src/main/res/drawable/ic_clock_timer.xml
  uicomponents/src/main/res/drawable/ic_location.xml
  uicomponents/src/test/java/com/valkiria/uicomponents/components/banner/BannerViewPaparazziTest.kt
  uicomponents/src/test/snapshots/images/com.valkiria.uicomponents.components.banner_BannerViewPaparazziTest_snapBannerView.png
Labels: feature

#144 [Test]: Device auth view model
  app/src/main/java/com/skgtecnologia/sisem/ui/deviceauth/DeviceAuthScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/deviceauth/DeviceAuthViewModel.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/authcards/create/AuthCardsViewModelTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewViewModelTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/deviceauth/DeviceAuthViewModelTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/login/LoginViewModelTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/splash/SplashViewModelTest.kt
Labels: test

#145 [Test]: Forgot password view model
  app/src/main/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordViewModel.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordViewModelTest.kt
Labels: test

#147 [Test]: Inventory view models
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/InventoryScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/InventoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/view/InventoryViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/view/InventoryViewViewModel.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/inventory/InventoryViewModelTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/inventory/view/InventoryViewViewModelTest.kt
Labels: test

#146 [Test]: Human body view model
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyBackComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyFrontComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyViewModel.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyViewModelTest.kt
Labels: test

#149 [Test]: stretcher retention and preoperational create and view - view models
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/StretcherRetentionScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/StretcherRetentionViewModel.kt
  app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalViewModelTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewViewModelTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/stretcherretention/StretcherRetentionViewModelTest.kt
Labels: test

#153 [Test]: Use cases
  app/src/main/java/com/skgtecnologia/sisem/domain/operation/usecases/ObserveOperationConfig.kt
  app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/auth/usecases/DeleteAccessTokenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/auth/usecases/GetAllAccessTokensTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/auth/usecases/LoginTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/auth/usecases/LogoutCurrentUserTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/auth/usecases/LogoutTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/authcards/usecases/GetAuthCardsScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/changepassword/usecases/ChangePasswordTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/changepassword/usecases/GetChangePasswordScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/changepassword/usecases/GetLoginNavigationModelTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/changepassword/usecases/OnCancelTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/deviceauth/usecases/AssociateDeviceTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/deviceauth/usecases/GetDeviceAuthScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/forgotpassword/usecases/GetForgotPasswordScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/forgotpassword/usecases/SendEmailTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/inventory/usecases/GetInventoryInitialScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/inventory/usecases/GetInventoryViewScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/login/usecases/GetLoginScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/BuildMedicineInformationTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/GetMedicalHistoryScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/GetMedicineScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/GetVitalSignsScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/SendMedicalHistoryTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/operation/usecases/GetOperationConfigTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/operation/usecases/GetStartupStateTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/operation/usecases/ObserveOperationConfigTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/preoperational/usecases/GetAuthCardViewScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/preoperational/usecases/GetPreOperationalScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/preoperational/usecases/GetPreOperationalScreenViewTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/preoperational/usecases/GetRoleTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/preoperational/usecases/SendPreOperationalTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/report/usecases/GetAddReportRoleScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/report/usecases/GetAddReportScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/report/usecases/SendReportTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/stretcherretention/usecases/GetStretcherRetentionScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/stretcherretention/usecases/SaveStretcherRetentionTest.kt
Labels: test

#152 [Chore]: Documentation
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItemsComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationCoordinator.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationRoutes.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
Labels: documentation

#154 [Test]: stretcher retentention - report and pre operational data module
  app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
  app/src/test/java/com/skgtecnologia/sisem/data/preoperational/PreOperationalRepositoryImplTest.kt
  app/src/test/java/com/skgtecnologia/sisem/data/preoperational/remote/PreOperationalRemoteDataSourceTest.kt
  app/src/test/java/com/skgtecnologia/sisem/data/report/ReportRepositoryImplTest.kt
  app/src/test/java/com/skgtecnologia/sisem/data/report/remote/ReportRemoteDataSourceTest.kt
  app/src/test/java/com/skgtecnologia/sisem/data/stretcherretention/StretcherRetentionRepositoryImplTest.kt
  app/src/test/java/com/skgtecnologia/sisem/data/stretcherretention/remote/StretcherRetentionRemoteDataSourceTest.kt
Labels: test

#155 [Fix]: SMA-315 and SMA-316 dissenting ordering between date and name in meds selector
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModelTest.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/chip/FilterChipView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/extensions/ChipExtensions.kt
Labels: bug

#156 [Bugfix]: Fix SMA-297
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/chip/ChipOptionsResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/chip/ChipSelectionResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/textfield/TextFieldResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/wounds/WoundsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/StretcherRetentionViewModel.kt
  app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
  gradle/libs.versions.toml
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/chip/OptionChipView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipOptionsUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/ChipOptionsUiModelMocks.kt
Labels: bug

#157 [Bugfix]: SMA-321
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/textfield/TextFieldResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/di/operation/OperationRole.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/addfinding/AddFindingScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/addreport/AddReportScreen.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/label/LabelComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/media/MediaActionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/extensions/FileExtensions.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/LabelUiModelMocks.kt
  uicomponents/src/test/snapshots/images/com.valkiria.uicomponents.components.label_LabelComponentPaparazziTest_snapLabelComponent.png
Labels: bug

#159 [Feature]: Push notifications complete
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/skgtecnologia/sisem/commons/communication/NotificationEventHandler.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/converters/CacheConverters.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notification/MessagingService.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notification/NotificationRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notification/NotificationsManager.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notification/cache/NotificationCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notification/cache/dao/NotificationDao.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notification/cache/model/NotificationEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notifications/NotificationsManager.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notifications/model/NotificationData.kt
  app/src/main/java/com/skgtecnologia/sisem/di/ApplicationModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreDatabaseModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/notification/NotificationRepositoryModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/notification/repository/NotificationRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/notification/usecases/StoreNotification.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewScreen.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalViewModelTest.kt
  gradle/libs.versions.toml
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/NotificationUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/NotificationView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/OnNotificationHandler.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/ClosingAPHNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/IncidentAssignedNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/IpsPatientTransferredNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/NoPreOperationalGeneratedCrueNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/NotificationData.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/NotificationType.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/StretcherRetentionEnableNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/SupportRequestNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/TransmilenioAuthorizationNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/TransmilenioDeniedNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/NotificationUiModelMocks.kt
  uicomponents/src/main/res/drawable/ic_road.xml
Labels: enhancement, feature

#161 [Fix]: Add validations for text fields in medical history
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/textfield/TextFieldResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalViewModelTest.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FilledTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/InputUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldUiModel.kt
Labels: bug

#163 [Bugfix]: Downgrade navigation compose version due to bug
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: bug

#162 [Fix]: Add RichLabel and Signature model to update their visibility
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/model/MedicalHistoryKeys.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
Labels: bug

#124 [Feat]: incident opening part 1
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/converters/CacheConverters.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/IncidentRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/IncidentCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/dao/IncidentDao.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/model/IncidentDetailEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/model/IncidentEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/model/IncidentTypeEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/model/PatientEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/model/ResourceDetailEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/model/ResourceEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/IncidentApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/IncidentRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/model/IncidentDetailResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/model/IncidentResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/model/IncidentTypeResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/model/PatientResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/model/ResourceDetailResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/model/ResourceResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notification/NotificationRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/OperationCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreDatabaseModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/incident/IncidentNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/incident/IncidentRepositoryModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/incident/IncidentRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/incident/usecases/ObserveActiveIncident.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItemsComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/media/ImagesConfirmationScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/NotificationUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/NotificationView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/IncidentAssignedNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/NotificationData.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/TransmilenioAuthorizationNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/TransmilenioDeniedNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/IncidentContent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/IncidentUiDetailModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/IncidentUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/IncidentUiTypeModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/PatientUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/ResourceUiDetailModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/ResourceUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
  uicomponents/src/main/res/drawable/ic_card_user.xml
  uicomponents/src/main/res/drawable/ic_chronometer.xml
  uicomponents/src/main/res/drawable/ic_circle.xml
  uicomponents/src/main/res/drawable/ic_clock_timer.xml
  uicomponents/src/main/res/drawable/ic_female.xml
  uicomponents/src/main/res/drawable/ic_firefighter.xml
  uicomponents/src/main/res/drawable/ic_idiger.xml
  uicomponents/src/main/res/drawable/ic_notification_alert.xml
  uicomponents/src/main/res/drawable/ic_patient.xml
  uicomponents/src/main/res/drawable/ic_police.xml
  uicomponents/src/main/res/drawable/ic_support.xml
Labels: feature

#165 [Feat] Signature register screen
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/signature/CrewMemberSignatureResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/screen/Params.kt
  app/src/main/java/com/skgtecnologia/sisem/data/signature/SignatureRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/signature/remote/SignatureApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/signature/remote/SignatureRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/signature/remote/model/SignatureBody.kt
  app/src/main/java/com/skgtecnologia/sisem/di/signature/SignatureNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/signature/SignatureRepositoryModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/signature/SignatureRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/signature/model/SignatureIdentifier.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/signature/usecases/GetInitSignatureScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/signature/usecases/GetSignatureScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/signature/usecases/RegisterSignature.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/signature/usecases/SearchDocument.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/DrawerMenuItemModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationCoordinator.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationRoutes.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/signature/init/InitSignatureNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/signature/init/InitSignatureScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/signature/init/InitSignatureUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/signature/init/InitSignatureViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/signature/view/SignatureNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/signature/view/SignatureScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/signature/view/SignatureUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/signature/view/SignatureViewModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/signature/CrewMemberSignatureComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/signature/CrewMemberSignatureUiModel.kt
Labels: feature

#167 [Feature]: Finish Incident Opening
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/MenuHeaderComponent.kt
  app/src/preProd/google-services.json
  app/src/preProd/res/values/strings.xml
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/IncidentContent.kt
  uicomponents/src/main/res/values/strings.xml
Labels: enhancement, feature

#169 [Feature]: Finish Incident Opening
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/converters/CacheConverters.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/model/IncidentEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/model/PatientEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/model/ResourceDetailEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/model/ResourceDetailResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/MedicalHistoryRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/MedicalHistoryRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/SendMedicalHistory.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationRoutes.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/SendMedicalHistoryTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/NotificationUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/NotificationData.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/TransmiNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/TransmilenioAuthorizationNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/model/TransmilenioDeniedNotification.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/IncidentContent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/IncidentUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/PatientUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/ResourceUiDetailModel.kt
  uicomponents/src/main/res/drawable/ic_smovilidad.xml
  uicomponents/src/main/res/values/strings.xml
Labels: feature

#166 [Feat]: Human body view component
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/body/HumanBodyViewResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/body/WoundResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/di/CoreNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/SwitchBodyType.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/area/BackArea.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/area/FrontArea.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/view/HumanBodyBackViewComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/view/HumanBodyFrontViewComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/view/HumanBodyViewComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/BodyRowType.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/humanbody/HumanBodyViewUiModel.kt
Labels: feature

#170 [Feat]: Incident screen
  app/src/main/java/com/skgtecnologia/sisem/data/incident/IncidentRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/IncidentApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/IncidentRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/bricks/chip/ChipSectionResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/card/InfoCardResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/card/PillResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/label/ListPatientResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/incident/IncidentRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/incident/usecases/GetIncidentScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/report/FindingsContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/incident/IncidentNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/incident/IncidentScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/incident/IncidentUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/incident/IncidentViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationCoordinator.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationRoutes.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/chip/ChipSectionUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/CardUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/PillUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/label/ListPatientUiModel.kt
  uicomponents/src/main/res/drawable/ic_bed.xml
Labels: feature

#168 [Fix]: Update withdrawal names in aph
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/model/MedicalHistoryKeys.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/model/WithdrawalText.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
Labels: bug

#173 [Feature]: Update Map BottomSheet
  .gitignore
  app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationCoordinator.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationRoutes.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
  app/src/test/java/com/skgtecnologia/sisem/data/stretcherretention/StretcherRetentionRepositoryImplTest.kt
  app/src/test/java/com/skgtecnologia/sisem/data/stretcherretention/remote/StretcherRetentionRemoteDataSourceTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/GetMedicalHistoryScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/SendMedicalHistoryTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/stretcherretention/usecases/GetStretcherRetentionScreenTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapBottomSheetView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapView.kt
Labels: enhancement, feature

#174 [Bugfix]: Android 0.10.0
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/DrawerContent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/footer/MenuFooterComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/CrewMemberItem.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/CrewMemberMenuItemModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/DrawerMenuItemModel.kt
Labels: bug
