Repository Valkiria-Project/SISEM-Android, pull requests merged in 2024-03, with the labels that each got.

#199 [Fix]: SMA-418
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/chip/ChipOptionsResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipOptionUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipOptionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipOptionsUiModel.kt
Labels: bug

#198 [Chore]: Android version to 1.2.0
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/ui/MainActivity.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/NotificationView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/signature/ComposeSignature.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/signature/SignatureComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/slider/SliderComponent.kt
Labels: bug

#201 [Fix]: SMA-390
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/timepicker/TimePickerComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/timepicker/TimePickerUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
  uicomponents/src/main/res/values/strings.xml
Labels: bug

#202 [Chore]: Release 1.3.0
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/MedicalHistoryRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/MedicalHistoryRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/SendMedicalHistory.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/MenuHeaderComponent.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ImageButtonSectionComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/button/OnClick.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionItemUiModel.kt
Labels: bug, enhancement, chore, feature

#203 [Chore]: Release 1.4.0
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportUiState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/media/ImagesConfirmationScreen.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/report/ReportViewModelTest.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/label/LabelComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/label/LabelUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/media/MediaActionsComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/media/MediaActionsUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/extensions/FileExtensions.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
Labels: bug, enhancement, feature
