Repository Valkiria-Project/SISEM-Android, pull requests merged in 2024-04, with the labels that each got.

#207 [Chore] Android release 1.5.3
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/VehicleConfigModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/menu/MenuViewModelTest.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapboxMapView.kt
Labels: bug, enhancement, chore

#208 [Chore] Android release 1.5.4
  .idea/kotlinc.xml
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/body/WoundResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/login/usecases/GetLoginScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyBackComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyFrontComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/view/HumanBodyBackViewComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/view/HumanBodyFrontViewComponent.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/view/HumanBodyViewComponent.kt
  app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  uicomponents/build.gradle.kts
  uicomponents/src/main/java/com/valkiria/uicomponents/components/humanbody/HumanBodyUi.kt
Labels: bug, enhancement, chore

#209 [Chore] Android release 1.5.5
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/skgtecnologia/sisem/commons/extensions/ContextExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/commons/extensions/ResultContracts.kt
  app/src/main/java/com/skgtecnologia/sisem/commons/location/DefaultLocationProvider.kt
  app/src/main/java/com/skgtecnologia/sisem/commons/location/LocationProvider.kt
  app/src/main/java/com/skgtecnologia/sisem/commons/location/LocationService.kt
  app/src/main/java/com/skgtecnologia/sisem/commons/resources/AndroidIdProviderImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/location/LocationRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/location/remote/LocationApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/location/remote/LocationRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/location/remote/model/LocationBody.kt
  app/src/main/java/com/skgtecnologia/sisem/data/stretcherretention/StretcherRetentionRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/di/ApplicationModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/location/LocationNetworkModule.kt
  app/src/main/java/com/skgtecnologia/sisem/di/location/LocationRepositoryModule.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/location/LocationRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/location/usecases/UpdateLocation.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/MainActivity.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/AuthCardsScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
Labels: bug, enhancement, feature

#210 [Chore] Android release 1.6.0
  .idea/misc.xml
  .idea/other.xml
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/model/IncidentEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/notification/NotificationRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/model/AccessTokenModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/usecases/Login.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/operation/model/PreoperationalStatus.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/operation/usecases/GetStartupState.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginNavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationCoordinator.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/auth/usecases/LoginTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/operation/usecases/GetStartupStateTest.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/button/ImageButtonUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/button/ImageButtonView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapboxMapView.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/IncidentUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/media/MediaActionsComponent.kt
Labels: bug, enhancement

#211 [Chore] Android release 1.7.0
  .idea/deviceManager.xml
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/ViewModelExtensions.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/create/StretcherRetentionScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/create/StretcherRetentionViewModel.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/stretcherretention/StretcherRetentionViewModelTest.kt
  gradle/libs.versions.toml
  uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/FiltersComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/FiltersUiModel.kt
Labels: bug, enhancement

#213 [Fix]: SMA-313 and SMA-434
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/dropdown/DropDownResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/dropdown/DropDownContent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView.kt
Labels: bug

#212 [Chore] Android release 1.8.0
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/ui/changepassword/ChangePasswordScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewScreen.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
  uicomponents/build.gradle.kts
  uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/FiltersComponent.kt
Labels: bug, enhancement

#215 [Chore] Android release 1.8.2
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/ui/theme/Type.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/label/TextStyle.kt
Labels: bug

#216 Fix: SMA-234
  uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/extensions/ModifierExtensions.kt
Labels: bug, enhancement

#217 [Chore] Android release 1.8.3
  app/build.gradle.kts
  app/src/main/java/com/skgtecnologia/sisem/commons/communication/UnauthorizedEventHandler.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/AuthCacheDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/dao/AccessTokenDao.kt
  app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/IncidentRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/incident/remote/model/PatientResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/OperationRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/model/OperationEntity.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/remote/OperationApi.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/remote/OperationRemoteDataSource.kt
  app/src/main/java/com/skgtecnologia/sisem/data/operation/remote/model/OperationResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/preoperational/PreOperationalRepositoryImpl.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenInterceptor.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/chip/ChipOptionsResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/chip/ChipSelectionResponse.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/auth/AuthRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/OperationModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/VehicleConfigModel.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/incident/IncidentRepository.kt
  app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/SendMedicalHistory.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/changepassword/ChangePasswordViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/incident/IncidentViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/InventoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/inventory/view/InventoryViewViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationRoutes.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/addreport/AddReportRoleViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/report/addreport/AddReportViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/sendemail/SendEmailViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/signature/init/InitSignatureViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/signature/view/SignatureViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/create/StretcherRetentionViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/pre/PreStretcherRetentionViewModel.kt
  app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/view/StretcherRetentionViewViewModel.kt
  app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
  app/src/test/java/com/skgtecnologia/sisem/data/preoperational/PreOperationalRepositoryImplTest.kt
  app/src/test/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/SendMedicalHistoryTest.kt
  app/src/test/java/com/skgtecnologia/sisem/ui/login/LoginViewModelTest.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/IncidentContent.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/PatientUiModel.kt
  uicomponents/src/main/java/com/valkiria/uicomponents/mocks/IncidentUiModelMocks.kt
Labels: bug, enhancement
